### ISSUE TITLE
大佬  pha4pgsql 会继续支持pg 12 、pg  13 吗

### ISSUE THREAD

**Issue by mysqlandy** [ChenHuajun/pha4pgsql#17]

**Comment by ChenHuajun** [comment]
目前我比较推荐使用patroni的方式搭建PG的HA。可以参考下面的方法

https://github.com/ChenHuajun/chenhuajun.github.io/blob/master/_posts/2020-09-07-%E5%9F%BA%E4%BA%8EPatroni%E7%9A%84PostgreSQL%E9%AB%98%E5%8F%AF%E7%94%A8%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2.md

对pha4pgsql，后面可以升级到支持PG12。
PG13对recovery.conf的改动比较大，就不打算继续支持了。（pha4pgsql的源头是https://github.com/ClusterLabs/resource-agents/heartbeat/pgsql ，resource-agents目前也还不支持PG13）
