### ISSUE TITLE
lib/common.sh函数可能有误

### ISSUE THREAD

**Issue by backusvan** [ChenHuajun/pha4pgsql#6]
您好，我在研究您的代码的过程中感觉，common.sh中的check_resource_started和stoped函数，for resource in $1，$1实际上每次都是获取第一个参数，无法获取整个参数列表，所以在cls_start 和cls_stop只是验证了第一个资源，后续的资源没有验证

**Comment by ChenHuajun** [comment]
以及fix，多谢！
