### ISSUE TITLE
PostgreSQL 11资源脚本bug

### ISSUE THREAD

**Issue by wenger1987** [ChenHuajun/pha4pgsql#7]
resource agent脚本，expgsql第2149行    $? -eq 2 里的$?被第一个判断修改了，ocf_version_cmp 结果应该使用变量保存才对

**Comment by ChenHuajun** [comment]
多谢报告！后面我测一下PG 11

**Comment by ChenHuajun** [comment]
多谢报告！后面我测一下PG 11

**Comment by ChenHuajun** [comment]
多谢报告！后面我测一下PG 11

**Comment by wenger1987** [comment]
> 多谢报告！后面我测一下PG 11

有两个地方都有这个问题，你可以检查一下

**Comment by ChenHuajun** [comment]
已修复
