### ISSUE TITLE
怎么不使用postgres用户？

### ISSUE THREAD

**Issue by zzl221000** [ChenHuajun/pha4pgsql#8]
因为不是标准的postgresql，没有用户postgres，clt_start后是使用postgres用户去启动程序？这个用户的配置是在哪呢？

**Comment by ChenHuajun** [comment]
你把下面这个参数改掉看看
https://github.com/ChenHuajun/pha4pgsql/blob/master/ra/expgsql

OCF_RESKEY_pgdba_default=postgres

**Comment by ChenHuajun** [comment]
也可以pcs命令给已经创建的pgsql资源添加一个pgdba参数
pgdba=xxxx

**Comment by ChenHuajun** [comment]
也可以pcs命令给已经创建的pgsql资源添加一个pgdba参数
pgdba=xxxx
或者改把参数加到配置模板里
https://github.com/ChenHuajun/pha4pgsql/blob/master/template/

**Comment by ChenHuajun** [comment]
也可以pcs命令给已经创建的pgsql资源添加一个pgdba参数
pgdba=xxxx
或者改把参数加到配置模板里
https://github.com/ChenHuajun/pha4pgsql/blob/master/template/

**Comment by zzl221000** [comment]
改了pgdba依然启动失败了，我这边的启动命令是agctl，之前是提示postgres用户不存在，现在是cannot start PostgreSQL

**Comment by zzl221000** [comment]
pcs启动的话是使用pgdba这个用户启动PostgreSQL吗，我这里的PostgreSQL环境变量只给了单个用户 @ChenHuajun

**Comment by ChenHuajun** [comment]
expgsql脚本用的  su - $OCF_RESKEY_pgdba -c ‘pg_ctl ...’执行的

    ocf_run $quietrun $loglevel $SU $OCF_RESKEY_pgdba -c "cd $OCF_RESKEY_pgdata; $*"

**Comment by ChenHuajun** [comment]
出现cannot start PostgreSQL ，你看下pg的错误日志

**Comment by ChenHuajun** [comment]
可以加一下我微信 chenhj_07

**Comment by ChenHuajun** [comment]
可以加一下我微信 chenhj_07

**Comment by zzl221000** [comment]
好的已加

**Comment by zzl221000** [comment]
记录下，pgbda指定用户，nic修改自己的网卡，primary_info 里面的user多余，放repuser这个参数就行
自己指定的库文件要在/usr/lib中建立软连接，写在环境变量中无效，
